### ISSUE TITLE
Idea: Detect encoding

### ISSUE THREAD

**Issue by burkasaurusrex** [mdcollins05/srt-lang-detect#1]
This is an awesome script - thanks for sharing it. I ran it on a huge untagged library of subtitles and it would fail seemingly randomly until I figured out that I had some subtitles with random character encoding. It would be cool to be able to detect the character encoding (maybe using [chardet](https://github.com/chardet/chardet)) and prompt the user if it isn't UTF-8? Or maybe convert to UTF-8?

**Comment by mdcollins05** [comment]
In some cases there are legit needs for other character encodings but those people probably know what they need. So it would need to be configurable.

Hmm, I'll have to think about this one and possibly how to implement it.

**Comment by cdelledonne** [comment]
I stumbled upon this as I'm having the same issue as the OP. I tried to look for possible solutions, and I came across [`charset_normalizer`](https://charset-normalizer.readthedocs.io/en/latest/index.html). It seems one can easily infer the language of a file using this library, *regardless of the file encoding*. Assuming `filepath` is the path of the subtitle file:
```py
from charset_normalizer import from_path
result = from_path(filepath).best()
language = result.language
```
If the confidence value is also needed:
```py
from charset_normalizer import from_path, detect
result = from_path(filepath).best()
confidence = detect(result.raw)['confidence']
```

Would be curious to hear your opinion on this. And thanks a lot for the script, very useful!

**Comment by mdcollins05** [comment]
A two for one sounds great. Would you be up for creating a PR? My free time is currently quite limited and I'm not sure when I'd be able to get around to it.

**Comment by cdelledonne** [comment]
I totally understand. Yes I'd be happy to submit a PR, will get back to you in some days.

**Comment by cdelledonne** [comment]
PR created: #5
