### ISSUE TITLE
chinese language subs not being detected / relabeled properly

### ISSUE THREAD

**Issue by sweaver2** [mdcollins05/srt-lang-detect#4]
when i run a chinese language srt through your tool, it's not matching on anything.

example below (srt uploaded as txt for github):
[Dunkirk (2017) (2017)_track10.txt](https://github.com/mdcollins05/srt-lang-detect/files/6172808/Dunkirk.2017.2017._track10.txt)

**Comment by mdcollins05** [comment]
Using that sample file, it is definitely having problems detecting the correct language. Here's the output:

```
> ./srtlangdetect.py -2 -s -v ./test.zh.srt
Parsing './test.zh.srt'...
Filename identified as: Chinese
Subtitles identified as:
Unknown: 71.43%
Korean: 28.57%
Cannot detect language of the subtitles in ./test.zh.srt
```

Unfortunately, I'm at the mercy of what the library that I use can detect. Specifically, I'm using the latest version of [langdetect](https://pypi.org/project/langdetect/).

Would an option to specify a default language work? If during the detection process, the top result is "Unknown", then the option would specify what we would assume the language is.

**Comment by sweaver2** [comment]
for me, it'd be easiest to just get a prompt saying something like "language could not be detected, would you like to specify a code", display the file name, and then prompt manual entry of the code.

usually these files i'm using have some kind of language description attached, it's just not the language code.
